version: '3'
services:
  app:
    build: .
    image: samuelastech/channel-videos
    container_name: app
    ports:
      - 3000:3000
    volumes:
      - ./:/app/
      - /app/node_modules
    command: ["npm", "run", "dev"]